### ISSUE TITLE
Sobre a bibliotecas ou ferramentas

### ISSUE THREAD

**Issue by Adailton90** [solutisfsw/desafio-multiverso-grafos#1]
Quando se fala nas regras:
"Você não poderá usar bibliotecas externas ou ferramentas resolver o problema das rotas."

Não se pode utilizar nenhum tipo de biblioteca ou ferramentas especificas para resolução de problemas de grafos, ou não pode utilizar nenhum tipo de recurso para facilitação do desenvolvimento.

Ex.: Criar projetos maven para Spring com dependências como Thymeleaf, JPA caso necessário, entre outros estariam fora das regras?

**Comment by solutisfsw** [comment]
Você não poderá usar bibliotecas na solução das **rotas/grafo**.
Para construção do projeto (back, front e testes) o uso é totalmente livre.

**Comment by Adailton90** [comment]
OK, obrigado
