### ISSUE TITLE
O que é considerado parada?

### ISSUE THREAD

**Issue by LuisAraujo** [solutisfsw/desafio-multiverso-grafos#9]
Por exemplo se eu saio de C e vou para C, passando apenas por D é considerado 1 parada (apenas o D), 2 paradas (D e C) ou 3 paradas (C, D, C)?

**Comment by solutisfsw** [comment]
Saindo de C e voltando a C, passando por D teremos apenas UMA parada. A parada em D.

**Comment by LuisAraujo** [comment]
Obrigado!
